### ISSUE TITLE
一直提示cookie可能失效

### ISSUE THREAD

**Issue by rei-smz** [Gaojianli/bupt-class-chooser#2]
登陆后从request header处获取cookie并修改config.json中的cookie，config.json中compulsory的值为true，RenXuanKe和hunger的值均为false。执行npm start后提示cookie可能失效，反复登入教务系统获取不同cookie仍报错。
详细错误信息如下：

> Cookie可能已失效,FetchError: request to https://jwgl.bupt.edu.cn/jsxsd/xsxk/xklc_list failed, reason: unable to verify the first certificate
> npm ERR! code ELIFECYCLE
> npm ERR! errno 255
> npm ERR! xuanke@1.1.0 start: `tsc && node build/spider.js`
> npm ERR! Exit status 255
> npm ERR! 
> npm ERR! Failed at the xuanke@1.1.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Gaojianli** [comment]
> reason: unable to verify the first certificate

 错误原因不是写的很明显嘛？你的证书有问题
